branches:
  except:
    - /^f\//
cache:
  directories:
    - node_modules
install:
  - make deps
script:
  - make
  - make test

language:
  - node_js
node_js:
  - node

dist: trusty
sudo: false

notifications:
  slack:
    rooms:
      - secure: "yHTXP3rjusOU3jKNIY6qw0Xeh4xgc/dvoFi//vlaL1nARpU5I//hoo/a3R5VLpQYSE3OHy7xd1OqgGQQJIOnt3ku6z4f45Panfx5CX7e3XpPIE9PZ6BNzWjVIBge9lNJ3atcrmMhFIkZ7Cbc9rleHG0KpEyNazC/qBpwjS9C/Vu/WckCP5eULkmHKVZznLjoyFXVmq+kg7OVa95Ss9Xni0Yvmj7gUTPBFmmccvpCI4P1M18lQMd17ZleQDbpJ7eHK2gjZcE/iIH63a4PqUo2SnD2qIx/ASrou8GoL4sNbenp/7hGIKkFtOOLqiV5OzDOWwjgxfE/InCbxDOdh4ui1Ck3Zxp88W/szVGcE3g2wF/DWRbCKw7WZa8hH8ZhmJZFuHhJCeK8E3WvpgetKMxxfDVCJtY8YzTCLpoEKks8hGY+NAhaMe564zp4mddeugcFwLbiM7XJKymnRQTQWu4QCHtqbz8SyIQLE3Z6+j1EEL4Cr8frXa/wLglGEMxx9bghXpuENDmmiVU+CTLnRSORMyIDAKsJFYevcHBjxeRUO8VNKg46B5UTJDXhgURTGHdAPjBJw+OpcIGHRlkjowCeWXgMQ3lZVq3XQ7VbO8MkdFI9W5J3GM0zDf67vIoDOvChkmwnbQxzpWf7e8anOoLe/sQa/b33mpdLWGuNOBPoJy0=" # atex-ci
      - secure: "ThQ98k4vrjXL39jN/khbzpcgJ/E6LEDHhkOwgMUrdKCsqRwUdpWz3OC4BzOmPw3hOF2tl7Oscs4C18p0OMRYs1ntX3oR8jD25+7d4yO3clwWW4zbBWOisnySYebmnh3E5Qak+Zmr9XpjoTSZIsNL3qbZ2N9nek2NQSO3/FYf4x/qvK4VJ7+tUlZqySelFTzN5jU+tfnHxFjRC+zOQISK1p0BoF83eaOKp3fpXxlgW/bXY2zPGvO8p+eWl1N0Rwwlkjor5pk9Jmf8B+ujur2R8PPImDS3q2Kn1DsDuXstqi3dc4di8kaWftHuCJDg7LcTTq/Gv7hoog8XWKipUOtw59RGyt23hWXoljaCTNoG59HZcJsAUXgTTUZNhToVX2zq0zfW+TLPrJcOVlzNIA48vIeRkqQM3o6THn/kK1HEALYBPiLD11Qej+Ucr1R1vuXYjVAvBR8BSaJJUqbjDFl2xJO8FYaokuWudAIFXnA9G9bsqmd85zPGUZHzvdXZmmA4qD3BNEEePzmu+3yQ388SYUCgi1xDl4MrChaEjWlrEqjTvzn+oX8QP7iK48ch8RyuftRvsreOJaA+xgJya3r7l/bEABlmWqMiDAv2ST1p+vRd+yAHlzmIG5dfZ9R+97EHVMxlEV/9q73OR6QyopqmueavMUH4pCzTAfDdhi8x2CQ=" # cloud-ci
    on_success: change
    on_pull_requests: false
